#data setup
source("./R/subscripts/centroid_assignment.R")
rm(list = ls())
source("./R/subscripts/data_prep.R")
rm(list = ls())

#run analyses
source("./R/subscripts/spatial_stats.R")
rm(list = ls())
source("./R/subscripts/get_sst_data.R")
rm(list = ls())
source("./R/subscripts/get_binned_vals.R")
rm(list = ls())

#figures
source("./R/figures/spatial_stats.R")
rm(list = ls())
source("./R/figures/spatial_stats_10myr.R")
rm(list = ls())
source("./R/figures/sst_plot.R")
rm(list = ls())
source("./R/figures/sst_plot_10myr.R")
rm(list = ls())
source("./R/figures/lat_temp_plot.R")
rm(list = ls())
source("./R/figures/map_plots_raster.R")
rm(list = ls())
source("./R/figures/aptian_plot.R")
rm(list = ls())
source("./R/figures/centroid_histogram.R")
rm(list = ls())
source("./R/figures/linear_models.R")
rm(list = ls())
source("./R/figures/continent_terrestrial_plot.R")
rm(list = ls())